import {type Constructor} from '@augment-vir/common';

/**
 * A string literal type that only matches the HTML spec tag names.
 *
 * @category Tag
 */
export type HtmlSpecTagName = keyof typeof htmlSpecConstructorsByTagName;

/**
 * All current HTML spec tag names mapped to their respective element constructors.
 *
 * Generated from `HTMLElementTagNameMap` in `typescript/lib/lib.dom.d.ts`:
 * https://raw.githubusercontent.com/microsoft/TypeScript/main/src/lib/dom.generated.d.ts
 *
 * @category Tag
 */
export const htmlSpecConstructorsByTagName = {
    a: globalThis.HTMLAnchorElement,
    abbr: globalThis.HTMLElement,
    address: globalThis.HTMLElement,
    area: globalThis.HTMLAreaElement,
    article: globalThis.HTMLElement,
    aside: globalThis.HTMLElement,
    audio: globalThis.HTMLAudioElement,
    b: globalThis.HTMLElement,
    base: globalThis.HTMLBaseElement,
    bdi: globalThis.HTMLElement,
    bdo: globalThis.HTMLElement,
    blockquote: globalThis.HTMLQuoteElement,
    body: globalThis.HTMLBodyElement,
    br: globalThis.HTMLBRElement,
    button: globalThis.HTMLButtonElement,
    canvas: globalThis.HTMLCanvasElement,
    caption: globalThis.HTMLTableCaptionElement,
    cite: globalThis.HTMLElement,
    code: globalThis.HTMLElement,
    col: globalThis.HTMLTableColElement,
    colgroup: globalThis.HTMLTableColElement,
    data: globalThis.HTMLDataElement,
    datalist: globalThis.HTMLDataListElement,
    dd: globalThis.HTMLElement,
    del: globalThis.HTMLModElement,
    details: globalThis.HTMLDetailsElement,
    dfn: globalThis.HTMLElement,
    dialog: globalThis.HTMLDialogElement,
    div: globalThis.HTMLDivElement,
    dl: globalThis.HTMLDListElement,
    dt: globalThis.HTMLElement,
    em: globalThis.HTMLElement,
    embed: globalThis.HTMLEmbedElement,
    fieldset: globalThis.HTMLFieldSetElement,
    figcaption: globalThis.HTMLElement,
    figure: globalThis.HTMLElement,
    footer: globalThis.HTMLElement,
    form: globalThis.HTMLFormElement,
    h1: globalThis.HTMLHeadingElement,
    h2: globalThis.HTMLHeadingElement,
    h3: globalThis.HTMLHeadingElement,
    h4: globalThis.HTMLHeadingElement,
    h5: globalThis.HTMLHeadingElement,
    h6: globalThis.HTMLHeadingElement,
    head: globalThis.HTMLHeadElement,
    header: globalThis.HTMLElement,
    hgroup: globalThis.HTMLElement,
    hr: globalThis.HTMLHRElement,
    html: globalThis.HTMLHtmlElement,
    i: globalThis.HTMLElement,
    iframe: globalThis.HTMLIFrameElement,
    img: globalThis.HTMLImageElement,
    input: globalThis.HTMLInputElement,
    ins: globalThis.HTMLModElement,
    kbd: globalThis.HTMLElement,
    label: globalThis.HTMLLabelElement,
    legend: globalThis.HTMLLegendElement,
    li: globalThis.HTMLLIElement,
    link: globalThis.HTMLLinkElement,
    main: globalThis.HTMLElement,
    map: globalThis.HTMLMapElement,
    mark: globalThis.HTMLElement,
    menu: globalThis.HTMLMenuElement,
    meta: globalThis.HTMLMetaElement,
    meter: globalThis.HTMLMeterElement,
    nav: globalThis.HTMLElement,
    noscript: globalThis.HTMLElement,
    object: globalThis.HTMLObjectElement,
    ol: globalThis.HTMLOListElement,
    optgroup: globalThis.HTMLOptGroupElement,
    option: globalThis.HTMLOptionElement,
    output: globalThis.HTMLOutputElement,
    p: globalThis.HTMLParagraphElement,
    picture: globalThis.HTMLPictureElement,
    pre: globalThis.HTMLPreElement,
    progress: globalThis.HTMLProgressElement,
    q: globalThis.HTMLQuoteElement,
    rp: globalThis.HTMLElement,
    rt: globalThis.HTMLElement,
    ruby: globalThis.HTMLElement,
    s: globalThis.HTMLElement,
    samp: globalThis.HTMLElement,
    script: globalThis.HTMLScriptElement,
    search: globalThis.HTMLElement,
    section: globalThis.HTMLElement,
    select: globalThis.HTMLSelectElement,
    slot: globalThis.HTMLSlotElement,
    small: globalThis.HTMLElement,
    source: globalThis.HTMLSourceElement,
    span: globalThis.HTMLSpanElement,
    strong: globalThis.HTMLElement,
    style: globalThis.HTMLStyleElement,
    sub: globalThis.HTMLElement,
    summary: globalThis.HTMLElement,
    sup: globalThis.HTMLElement,
    table: globalThis.HTMLTableElement,
    tbody: globalThis.HTMLTableSectionElement,
    td: globalThis.HTMLTableCellElement,
    template: globalThis.HTMLTemplateElement,
    textarea: globalThis.HTMLTextAreaElement,
    tfoot: globalThis.HTMLTableSectionElement,
    th: globalThis.HTMLTableCellElement,
    thead: globalThis.HTMLTableSectionElement,
    time: globalThis.HTMLTimeElement,
    title: globalThis.HTMLTitleElement,
    tr: globalThis.HTMLTableRowElement,
    track: globalThis.HTMLTrackElement,
    u: globalThis.HTMLElement,
    ul: globalThis.HTMLUListElement,
    var: globalThis.HTMLElement,
    video: globalThis.HTMLVideoElement,
    wbr: globalThis.HTMLElement,
} as const satisfies Readonly<Record<string, Constructor<HTMLElement>>>;

/**
 * All possible HTML spec tag names within a single array.
 *
 * @category Tag
 */
export const allHtmlSpecTagNames: ReadonlyArray<HtmlSpecTagName> = Object.keys(
    htmlSpecConstructorsByTagName,
) as ReadonlyArray<HtmlSpecTagName>;
